# ----
# Site

title: rīvolō
url: "https://rivolo-studios.com/"
baseurl: ""
stripe:
  success_path: "/success"
  cancel_path: "/cancel"
google_analytics_key:
google_maps_javascript_api_key:
google_tag_manager_id: "GTM-W6P5JFGP"
snipcart_key: 
snipcart_currency: "eur"
stripe_publishable_key: "pk_live_51QvFWaLXseLV5m3AuMDvymWsFdM10rU1yE0Okmj5ekbS4CsquxHVDfBOYLS6KnPXv6h28ydcrM6vquTPQvjgFGbH00b8UOefNg" # Add this line
stripe_publishable_key_test: "pk_test_51QvFWaLXseLV5m3AjppuUGN6Q6py7pG6JXB2L3ZPvvHMlWKX8AKU2vSdMHW2wtNUg0lx08QBh1wYPIAlleZE6702007pzWvkOy"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/brand_logo_white.svg
description: E-commerce store for reusable coffee cups from Huskee
author:
  name: rivolo-studios
  email: info@rivolo-studios.com
  pinterest: #fur # twitter username without the @ symbol
  phone: "+49 172 5892696"
social:
  name: Pinterest 
  links:
    - https://pinterest.com/rivolostudios

# -----
# Build
timezone: ETC/UTC

collections:
  products:
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-google-tag-manager

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - Dockerfile
  - docker-compose.yml
  - .dockerignore
  - .gitignore
  - .sass-cache
  - .jekyll-cache
  - node_modules
  - _site
  - assets/css/main.scss

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
