
services:
  app:
    container_name: jekyll_container
    build:
      context: .
      dockerfile: Dockerfile
    image: jekyll_image
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll